name: Code_Inspector
on: [push]

jobs:
  build:
    name: CodeInspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install CodeInspector
        run: sudo apt-get -y install CodeInspector
      - name: CodeInspector code
        run: CodeInspector 3_Implementation
